name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
        with:
          build: npm run build
          start: npm start
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test